### PR TITLE
Execute avrdude in background & Projects support

### PR DESCRIPTION
**Pull request by trol73**
Hi, I made some improvements in the project which I personally really lacked for my work:
- avrdude now executes in background thread, no ui freeze more
- projects support (main menu -> Projects), now you can quickly switch between different projects
- context menu for avrdude output view (clear/copy)
- Preferences dialog now can be closed on Esc
- deprecated methods are replaced to actual, fixed all warnings

### CODE REVIEW

**Comment by vonnieda** [comment]
Hi @trol73, these look like very nice changes, but I am running into a background crash when trying to use the Autodetect feature. This results in a stack trace in Xcode but nothing shown to the user. Stack trace is:
```
2017-09-25 19:54:54.556898-0500 AVRFuses[86636:7504469] [General] *** -[__NSArrayM insertObject:atIndex:]: object cannot be nil
2017-09-25 19:54:54.561096-0500 AVRFuses[86636:7504469] [General] (
	0   CoreFoundation                      0x00007fff7fea157b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff950fa1da objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff7fdbd51d -[__NSArrayM insertObject:atIndex:] + 1389
	3   AVRFuses                            0x000000010000548a -[AVRFusesController defaultAvrdudeArguments] + 426
	4   AVRFuses                            0x00000001000076b7 -[AVRFusesController autodetectDevice:] + 39
	5   libsystem_trace.dylib               0x00007fff95c0d3a7 _os_activity_initiate_impl + 53
	6   AppKit                              0x00007fff7e08e721 -[NSApplication(NSResponder) sendAction:to:from:] + 456
	7   AppKit                              0x00007fff7db72cc4 -[NSControl sendAction:to:] + 86
	8   AppKit                              0x00007fff7db72bec __26-[NSCell _sendActionFrom:]_block_invoke + 136
	9   libsystem_trace.dylib               0x00007fff95c0d3a7 _os_activity_initiate_impl + 53
	10  AppKit                              0x00007fff7db72b44 -[NSCell _sendActionFrom:] + 128
	11  AppKit                              0x00007fff7dbb5539 -[NSButtonCell _sendActionFrom:] + 98
	12  libsystem_trace.dylib               0x00007fff95c0d3a7 _os_activity_initiate_impl + 53
	13  AppKit                              0x00007fff7db71426 -[NSCell trackMouse:inRect:ofView:untilMouseUp:] + 2481
	14  AppKit                              0x00007fff7dbb5272 -[NSButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 798
	15  AppKit                              0x00007fff7db6fddb -[NSControl mouseDown:] + 832
	16  AppKit                              0x00007fff7e20a24f -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 6341
	17  AppKit                              0x00007fff7e206a6c -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 1942
	18  AppKit                              0x00007fff7e205f0a -[NSWindow(NSEventRouting) sendEvent:] + 541
	19  AppKit                              0x00007fff7e08a681 -[NSApplication(NSEvent) sendEvent:] + 1145
	20  AppKit                              0x00007fff7d905427 -[NSApplication run] + 1002
	21  AppKit                              0x00007fff7d8cfe0e NSApplicationMain + 1237
	22  AVRFuses                            0x00000001000019a7 main + 231
	23  libdyld.dylib                       0x00007fff959db235 start + 1
	24  ???                                 0x0000000000000003 0x0 + 3
)
```

**Comment by trol73** [comment]
Hi @vonnieda,
I have fixed it. Also I have enabled avrdude progress bar on operation

**Comment by vonnieda** [comment]
Thanks @trol73, I will test it this weekend and prep a new release if it's all looking good.

**Comment by vonnieda** [comment]
Looks good, thanks @trol73! I'll merge this now and do a release update as soon as I can.

**Comment by vonnieda** [comment]
Version 1.5.0 released. Thanks @trol73!

**Pull request merged**
